version: '2'
services:

  apiman:
    build: ./docker/apiman
    ports:
      - '9080:8080'
      - '9443:8443'
    links:
      - api
      - echo 

  configr:
    build: ./docker/configr

  echo:
    build: ./docker/echo-api
    ports:
      - '5000:5000'

  api:
    build: ../hmda-platform

  web:
    build: ../hmda-platform-ui
    ports:
      - '80:80'
    depends_on:
      - configr
