FROM apiman/on-wildfly10:1.2.7.Final

#COPY ./keycloak/configuration/keycloak-server.json:/opt/jboss/wildfly/standalone/configuration/keycloak-server.json
COPY ./keycloak/ /opt/jboss/wildfly/standalone/
